#######################################################
# https://hub.docker.com/_/microsoft-azure-sql-edge
# docker-compose up -d
# docker-compose down
#######################################################
version: '3.3'
services:
  db:
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    user: root
    container_name: sqledge
    ports:
      - '1433:1433'
    volumes:
      - '////c/vm/db/mssql/data_edge:/var/opt/mssql/data'
      - '////c/vm/db/mssql/log:/var/opt/mssql/log'
      - '////c/vm/db/mssql/secrets:/var/opt/mssql/secrets'
    environment:
      MSSQL_SA_PASSWORD: 'mypassword123'  # username: sa
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer' # or Premium
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    restart: unless-stopped
