###########################################################
# Commands below goes against this docker-compose.yml file
# https://hub.docker.com/_/microsoft-mssql-server
# docker-compose up -d
# docker-compose down
############################################################
version: '3.9'
services:
  db:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    container_name: mssql
    ports:
      - '1433:1433'
    volumes:
      - '////c/vm/db/mssql/data:/var/opt/mssql/data'
    environment:
      SA_PASSWORD: 'mypassword123'  # username: sa
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  mssql_default:
    external: true
